development: &default
  adapter: postgresql
  database: tdd_example_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: localhost
  port:     <%= ENV.fetch("db_port") %>
  username: <%= ENV.fetch("db_username") %>
  password: <%= ENV.fetch("db_password") %>

test:
  <<: *default
  database: tdd_example_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
